export const assets = {
  logo: "/images/sky/logo.png",
  heroBackground: "/images/sky/hero-background.png",
  avatars: [
    "/images/sky/avatar-0.png",
    "/images/sky/avatar-1.png",
    "/images/sky/avatar-2.png",
    "/images/sky/avatar-3.png",
  ],
  pillars: {
    awareness: "/images/sky/hero-background.png",
    understanding: "/images/sky/pillar-understanding.png",
    guidance: "/images/sky/pillar-guidance.png",
    consistency: "/images/sky/pillar-consistency.png",
  },
  meetSkyBackground: "/images/sky/meet-sky-background.png",
  iconCircleBlue: "/images/sky/icon-circle-blue.svg",
  iconCircleGreen: "/images/sky/icon-circle-green.svg",
  iconCircleOrange: "/images/sky/icon-circle-orange.svg",
  dashboardBackground: "/images/sky/dashboard-background.png",
  phoneMockup: "/images/sky/phone-mockup.png",
  timeline: [
    "/images/sky/timeline-0.png",
    "/images/sky/timeline-1.png",
    "/images/sky/timeline-2.png",
    "/images/sky/timeline-3.png",
    "/images/sky/timeline-4.png",
    "/images/sky/timeline-5.png",
  ],
  experts: {
    featured: "/images/sky/expert-featured.png",
    secondary: [
      "/images/sky/expert-secondary-0.png",
      "/images/sky/expert-secondary-1.png",
      "/images/sky/expert-secondary-2.png",
    ],
  },
  finalCtaBackground: "/images/sky/final-cta-background.png",
  ring: "/images/sky/cta-ring.png",
  footer: {
    socialCircle: "/images/footer/social-circle.svg",
    masks: {
      chevron: "/images/footer/mask-chevron.png",
      location: "/images/footer/mask-location.png",
      email: "/images/footer/mask-email.png",
      phone: "/images/footer/mask-phone.png",
      wave: "/images/footer/mask-wave.png",
      facebook: "/images/footer/mask-facebook.png",
      twitter: "/images/footer/mask-twitter.png",
      instagram: "/images/footer/mask-instagram.png",
      youtube: "/images/footer/mask-youtube.png",
    },
    social: {
      facebook: "/images/footer/social-facebook.png",
      twitter: "/images/footer/social-twitter.png",
      instagram: "/images/footer/social-instagram.png",
      youtube: "/images/footer/social-youtube.png",
    },
  },
} as const;
