export const icons = {
  play: "/icons/play.svg",
  arrow: "/icons/arrow.svg",
  arrowRight: "/icons/arrow-right.svg",
  circleDashed: "/icons/circle-dashed.svg",
  brain: "/icons/brain.svg",
  leaf: "/icons/leaf.svg",
  community: "/icons/community.svg",
  powerSleep: "/icons/power-sleep.svg",
  oxygen: "/icons/oxygen.svg",
  running: "/icons/running.svg",
  stress: "/icons/stress.svg",
  leafFill: "/icons/leaf-fill.svg",
  heartbeat: "/icons/heartbeat.svg",
  premium: "/icons/premium.svg",
  waterdrop: "/icons/waterdrop.svg",
  battery: "/icons/battery.svg",
  wave: "/icons/wave.svg",
  bell: "/icons/bell.svg",
  personArmsUp: "/icons/person-arms-up.svg",
  sunHigh: "/icons/sun-high.svg",
  sunrise: "/icons/sunrise.svg",
  waveSaw: "/icons/wave-saw.svg",
  scanner: "/icons/scanner.svg",
  moonSleep: "/icons/moon-sleep.svg",
  foodApple: "/icons/food-apple.svg",
  personRun: "/icons/person-run.svg",
  userRounded: "/icons/user-rounded.svg",
  shieldCheck: "/icons/shield-check.svg",
  flowerLotus: "/icons/flower-lotus.svg",
  hearts: "/icons/hearts.svg",
  flowerLotusDuotone: "/icons/flower-lotus-duotone.svg",
  star: "/icons/star.svg",
  yoga: "/icons/yoga.svg",
  heart: "/icons/heart.svg",
  chevron: "/icons/chevron.png",
  social: "/icons/social.png",
  location: "/icons/location.png",
  email: "/icons/email.png",
  phone: "/icons/phone.png",
} as const;

export type IconName = keyof typeof icons;
